In [1]:
import pandas as pd
import numpy
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [2]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [3]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [4]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [5]:
dependent=dataset[['charges']]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [6]:
dependent = numpy.ravel(dependent)
#y_test = numpy.ravel(y_test)

In [7]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {'kernel':['rbf','poly','sigmoid','linear'],'C':[10,100,1000,2000,3000]}
#'gamma':['auto','scale']
grid=GridSearchCV(SVR(), param_grid, refit=True,verbose=3, n_jobs=1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 20 candidates, totalling 100 fits
[CV 1/5] END .................C=10, kernel=rbf;, score=-0.110 total time=   0.0s
[CV 2/5] END .................C=10, kernel=rbf;, score=-0.097 total time=   0.0s
[CV 3/5] END .................C=10, kernel=rbf;, score=-0.074 total time=   0.0s
[CV 4/5] END .................C=10, kernel=rbf;, score=-0.100 total time=   0.0s
[CV 5/5] END .................C=10, kernel=rbf;, score=-0.124 total time=   0.0s
[CV 1/5] END ................C=10, kernel=poly;, score=-0.125 total time=   0.0s
[CV 2/5] END ................C=10, kernel=poly;, score=-0.082 total time=   0.0s
[CV 3/5] END ................C=10, kernel=poly;, score=-0.112 total time=   0.0s
[CV 4/5] END ................C=10, kernel=poly;, score=-0.132 total time=   0.0s
[CV 5/5] END ................C=10, kernel=poly;, score=-0.179 total time=   0.0s
[CV 1/5] END .............C=10, kernel=sigmoid;, score=-0.117 total time=   0.0s
[CV 2/5] END .............C=10, kernel=sigmoid;, score=-0.119 total time=   0.0s
[CV 3/5] END .............C=10, kernel=sigmoid;, score=-0.085 total time=   0.0s
[CV 4/5] END .............C=10, kernel=sigmoid;, score=-0.108 total time=   0.0s
[CV 5/5] END .............C=10, kernel=sigmoid;, score=-0.109 total time=   0.0s
[CV 1/5] END ..............C=10, kernel=linear;, score=-0.019 total time=   0.0s
[CV 2/5] END ...............C=10, kernel=linear;, score=0.030 total time=   0.0s
[CV 3/5] END ...............C=10, kernel=linear;, score=0.022 total time=   0.0s
[CV 4/5] END ...............C=10, kernel=linear;, score=0.003 total time=   0.0s
[CV 5/5] END ..............C=10, kernel=linear;, score=-0.067 total time=   0.0s
[CV 1/5] END ................C=100, kernel=rbf;, score=-0.160 total time=   0.0s
[CV 2/5] END ................C=100, kernel=rbf;, score=-0.107 total time=   0.0s
[CV 3/5] END ................C=100, kernel=rbf;, score=-0.123 total time=   0.0s
[CV 4/5] END ................C=100, kernel=rbf;, score=-0.138 total time=   0.0s
[CV 5/5] END ................C=100, kernel=rbf;, score=-0.210 total time=   0.0s
[CV 1/5] END ...............C=100, kernel=poly;, score=-0.133 total time=   0.0s
[CV 2/5] END ...............C=100, kernel=poly;, score=-0.082 total time=   0.0s
[CV 3/5] END ...............C=100, kernel=poly;, score=-0.129 total time=   0.0s
[CV 4/5] END ...............C=100, kernel=poly;, score=-0.140 total time=   0.0s
[CV 5/5] END ...............C=100, kernel=poly;, score=-0.189 total time=   0.0s
[CV 1/5] END ............C=100, kernel=sigmoid;, score=-0.142 total time=   0.0s
[CV 2/5] END ............C=100, kernel=sigmoid;, score=-0.161 total time=   0.0s
[CV 3/5] END ............C=100, kernel=sigmoid;, score=-0.118 total time=   0.0s
[CV 4/5] END ............C=100, kernel=sigmoid;, score=-0.138 total time=   0.0s
[CV 5/5] END ............C=100, kernel=sigmoid;, score=-0.130 total time=   0.0s
[CV 1/5] END ..............C=100, kernel=linear;, score=0.559 total time=   0.0s
[CV 2/5] END ..............C=100, kernel=linear;, score=0.522 total time=   0.0s
[CV 3/5] END ..............C=100, kernel=linear;, score=0.548 total time=   0.0s
[CV 4/5] END ..............C=100, kernel=linear;, score=0.539 total time=   0.0s
[CV 5/5] END ..............C=100, kernel=linear;, score=0.509 total time=   0.0s
[CV 1/5] END ...............C=1000, kernel=rbf;, score=-0.155 total time=   0.0s
[CV 2/5] END ...............C=1000, kernel=rbf;, score=-0.098 total time=   0.0s
[CV 3/5] END ...............C=1000, kernel=rbf;, score=-0.124 total time=   0.0s
[CV 4/5] END ...............C=1000, kernel=rbf;, score=-0.137 total time=   0.0s
[CV 5/5] END ...............C=1000, kernel=rbf;, score=-0.206 total time=   0.0s
[CV 1/5] END ..............C=1000, kernel=poly;, score=-0.081 total time=   0.0s
[CV 2/5] END ..............C=1000, kernel=poly;, score=-0.028 total time=   0.0s
[CV 3/5] END ..............C=1000, kernel=poly;, score=-0.073 total time=   0.0s
[CV 4/5] END ..............C=1000, kernel=poly;, score=-0.087 total time=   0.0s
[CV 5/5] END ..............C=1000, kernel=poly;, score=-0.134 total time=   0.0s
[CV 1/5] END ...........C=1000, kernel=sigmoid;, score=-2.043 total time=   0.0s
[CV 2/5] END ...........C=1000, kernel=sigmoid;, score=-2.686 total time=   0.0s
[CV 3/5] END ...........C=1000, kernel=sigmoid;, score=-2.195 total time=   0.0s
[CV 4/5] END ...........C=1000, kernel=sigmoid;, score=-2.211 total time=   0.0s
[CV 5/5] END ...........C=1000, kernel=sigmoid;, score=-1.943 total time=   0.0s
[CV 1/5] END .............C=1000, kernel=linear;, score=0.736 total time=   0.2s
[CV 2/5] END .............C=1000, kernel=linear;, score=0.675 total time=   0.3s
[CV 3/5] END .............C=1000, kernel=linear;, score=0.680 total time=   0.2s
[CV 4/5] END .............C=1000, kernel=linear;, score=0.699 total time=   0.2s
[CV 5/5] END .............C=1000, kernel=linear;, score=0.678 total time=   0.6s
[CV 1/5] END ...............C=2000, kernel=rbf;, score=-0.144 total time=   0.1s
[CV 2/5] END ...............C=2000, kernel=rbf;, score=-0.088 total time=   0.1s
[CV 3/5] END ...............C=2000, kernel=rbf;, score=-0.113 total time=   0.0s
[CV 4/5] END ...............C=2000, kernel=rbf;, score=-0.129 total time=   0.1s
[CV 5/5] END ...............C=2000, kernel=rbf;, score=-0.194 total time=   0.1s
[CV 1/5] END ..............C=2000, kernel=poly;, score=-0.021 total time=   0.1s
[CV 2/5] END ...............C=2000, kernel=poly;, score=0.036 total time=   0.1s
[CV 3/5] END ..............C=2000, kernel=poly;, score=-0.011 total time=   0.1s
[CV 4/5] END ..............C=2000, kernel=poly;, score=-0.025 total time=   0.1s
[CV 5/5] END ..............C=2000, kernel=poly;, score=-0.076 total time=   0.1s
[CV 1/5] END ...........C=2000, kernel=sigmoid;, score=-7.209 total time=   0.1s
[CV 2/5] END ...........C=2000, kernel=sigmoid;, score=-9.283 total time=   0.1s
[CV 3/5] END ...........C=2000, kernel=sigmoid;, score=-7.777 total time=   0.1s
[CV 4/5] END ...........C=2000, kernel=sigmoid;, score=-7.745 total time=   0.1s
[CV 5/5] END ...........C=2000, kernel=sigmoid;, score=-6.892 total time=   0.1s
[CV 1/5] END .............C=2000, kernel=linear;, score=0.682 total time=   1.1s
[CV 2/5] END .............C=2000, kernel=linear;, score=0.631 total time=   0.8s
[CV 3/5] END .............C=2000, kernel=linear;, score=0.751 total time=   1.5s
[CV 4/5] END .............C=2000, kernel=linear;, score=0.646 total time=   1.3s
[CV 5/5] END .............C=2000, kernel=linear;, score=0.722 total time=   1.0s
[CV 1/5] END ...............C=3000, kernel=rbf;, score=-0.129 total time=   0.1s
[CV 2/5] END ...............C=3000, kernel=rbf;, score=-0.076 total time=   0.1s
[CV 3/5] END ...............C=3000, kernel=rbf;, score=-0.100 total time=   0.1s
[CV 4/5] END ...............C=3000, kernel=rbf;, score=-0.116 total time=   0.1s
[CV 5/5] END ...............C=3000, kernel=rbf;, score=-0.179 total time=   0.1s
[CV 1/5] END ...............C=3000, kernel=poly;, score=0.038 total time=   0.1s
[CV 2/5] END ...............C=3000, kernel=poly;, score=0.098 total time=   0.1s
[CV 3/5] END ...............C=3000, kernel=poly;, score=0.049 total time=   0.1s
[CV 4/5] END ...............C=3000, kernel=poly;, score=0.036 total time=   0.1s
[CV 5/5] END ..............C=3000, kernel=poly;, score=-0.021 total time=   0.1s
[CV 1/5] END ..........C=3000, kernel=sigmoid;, score=-15.562 total time=   0.1s
[CV 2/5] END ..........C=3000, kernel=sigmoid;, score=-20.499 total time=   0.1s
[CV 3/5] END ..........C=3000, kernel=sigmoid;, score=-17.095 total time=   0.1s
[CV 4/5] END ..........C=3000, kernel=sigmoid;, score=-16.751 total time=   0.1s
[CV 5/5] END ..........C=3000, kernel=sigmoid;, score=-15.012 total time=   0.1s
[CV 1/5] END .............C=3000, kernel=linear;, score=0.678 total time=   2.0s
[CV 2/5] END .............C=3000, kernel=linear;, score=0.627 total time=   1.8s
[CV 3/5] END .............C=3000, kernel=linear;, score=0.733 total time=   1.9s
[CV 4/5] END .............C=3000, kernel=linear;, score=0.633 total time=   3.6s
[CV 5/5] END .............C=3000, kernel=linear;, score=0.699 total time=   1.6s

GridSearchCV(estimator=SVR(), n_jobs=1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             verbose=3)

In [8]:
re=grid.cv_results_

print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'C': 1000, 'kernel': 'linear'}:

In [9]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.055577,0.012408,0.026970,0.004222,10,rbf,"{'C': 10, 'kernel': 'rbf'}",-0.110409,-0.097459,-0.074488,-0.099597,-0.124428,-0.101276,0.016459,9
1,0.049839,0.009603,0.008539,0.002630,10,poly,"{'C': 10, 'kernel': 'poly'}",-0.125153,-0.081505,-0.111907,-0.131602,-0.179328,-0.125899,0.031794,12
2,0.065088,0.004330,0.017680,0.005084,10,sigmoid,"{'C': 10, 'kernel': 'sigmoid'}",-0.116743,-0.119312,-0.085214,-0.108210,-0.108716,-0.107639,0.012029,10
3,0.057186,0.008580,0.009191,0.004054,10,linear,"{'C': 10, 'kernel': 'linear'}",-0.018943,0.029886,0.022167,0.003112,-0.066653,-0.006086,0.034672,6
4,0.052923,0.006390,0.024516,0.002035,100,rbf,"{'C': 100, 'kernel': 'rbf'}",-0.160182,-0.107253,-0.123430,-0.137753,-0.209551,-0.147634,0.035511,17
5,0.046659,0.003568,0.008866,0.003664,100,poly,"{'C': 100, 'kernel': 'poly'}",-0.132885,-0.082461,-0.129220,-0.139962,-0.189219,-0.134749,0.033948,14
6,0.061754,0.003467,0.013327,0.001158,100,sigmoid,"{'C': 100, 'kernel': 'sigmoid'}",-0.142455,-0.160831,-0.117544,-0.137984,-0.130402,-0.137843,0.014263,15
7,0.096637,0.008769,0.007979,0.001746,100,linear,"{'C': 100, 'kernel': 'linear'}",0.559313,0.521798,0.547691,0.538805,0.508518,0.535225,0.018122,4
8,0.058035,0.003369,0.028518,0.005255,1000,rbf,"{'C': 1000, 'kernel': 'rbf'}",-0.155430,-0.098267,-0.123724,-0.137137,-0.206405,-0.144193,0.036262,16
9,0.069489,0.008681,0.010248,0.003582,1000,poly,"{'C': 1000, 'kernel': 'poly'}",-0.080527,-0.028469,-0.073376,-0.086611,-0.134493,-0.080695,0.033795,8
10,0.066125,0.004457,0.013810,0.001201,1000,sigmoid,"{'C': 1000, 'kernel': 'sigmoid'}",-2.043140,-2.686121,-2.194563,-2.210858,-1.942521,-2.215441,0.255409,18
11,0.397750,0.126442,0.008769,0.003450,1000,linear,"{'C': 1000, 'kernel': 'linear'}",0.736398,0.675162,0.680002,0.699377,0.677952,0.693778,0.022955,1
12,0.120069,0.011813,0.053145,0.011180,2000,rbf,"{'C': 2000, 'kernel': 'rbf'}",-0.143510,-0.087595,-0.113312,-0.128591,-0.193992,-0.133400,0.035492,13
13,0.160983,0.004745,0.017995,0.001502,2000,poly,"{'C': 2000, 'kernel': 'poly'}",-0.020567,0.035685,-0.011468,-0.024587,-0.076360,-0.019459,0.035693,7
14,0.149720,0.007575,0.032423,0.001275,2000,sigmoid,"{'C': 2000, 'kernel': 'sigmoid'}",-7.209317,-9.282940,-7.776578,-7.745074,-6.891719,-7.781126,0.821557,19
15,1.249323,0.226981,0.016127,0.001114,2000,linear,"{'C': 2000, 'kernel': 'linear'}",0.682349,0.630642,0.750714,0.646368,0.722261,0.686467,0.045056,2
16,0.157847,0.010698,0.063339,0.005379,3000,rbf,"{'C': 3000, 'kernel': 'rbf'}",-0.128958,-0.075578,-0.100199,-0.116051,-0.179304,-0.120018,0.034578,11
17,0.187438,0.026044,0.017802,0.005821,3000,poly,"{'C': 3000, 'kernel': 'poly'}",0.037700,0.098496,0.049291,0.035615,-0.020924,0.040035,0.038064,5
18,0.181329,0.027237,0.035180,0.006468,3000,sigmoid,"{'C': 3000, 'kernel': 'sigmoid'}",-15.561853,-20.498908,-17.095474,-16.750877,-15.012168,-16.983856,1.914783,20
19,2.260781,0.723311,0.015066,0.002600,3000,linear,"{'C': 3000, 'kernel': 'linear'}",0.677778,0.626814,0.732806,0.633479,0.698692,0.673914,0.039876,3

In [10]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:29
BMI:35
Children:2
Sex Male 0 or 1:0
Smoker Yes 0 or 1:1

In [11]:
prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
prediction

C:\Users\poorn\Anaconda3\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  "X does not have valid feature names, but"

array([29589.882503])

In [12]:
import pickle
filename="finalized_RFGRIDsearchCV_model.sav"
#writing the model in a new file
pickle.dump(grid,open(filename,'wb'))

In [13]:
loaded_modal=pickle.load(open("finalized_RFGRIDsearchCV_model.sav",'rb'))
result=loaded_modal.predict([[29,35,2,0,1]])
result

C:\Users\poorn\Anaconda3\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  "X does not have valid feature names, but"

array([29589.882503])